name: Build with PyInstaller

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.12'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pyinstaller
        pip install -r requirements.txt
      shell: cmd

    - name: Build with PyInstaller
      run: |
        pyinstaller --onefile --add-data "site-packages\escpos\capabilities.json;escpos" main.py
      shell: cmd

    - name: Upload build artifacts
      uses: actions/upload-artifact@v3
      with:
        name: app-executable
        path: dist/